### ISSUE TITLE
Edit button not always appearing

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#103] opened 2022-05-24 13:27 UTC
The edit button appears on some items but not others. (See examples below). We are using the Tiles course format. Might that be the issue?

Example 1: Appears on topic headings, but not against labels.

![image](https://user-images.githubusercontent.com/2512079/170046201-a0412e7c-afc4-40ba-b844-b05ab26ca041.png)

Example 2: Appears on some topic headings but not others

![image](https://user-images.githubusercontent.com/2512079/170046297-0fa1e14d-4007-4b5f-9c6a-a7045b86c8b4.png)

Example 3: Doesn't appear on pages

![image](https://user-images.githubusercontent.com/2512079/170046466-05294efa-c45c-439c-9e35-81fd041e885d.png)

**Comment by jgramp** [comment] 2022-05-24 18:00
Have you checked if the icon is appearing behind the images? I believe we had this issue previously.
I proposed at the time:

Make sure the translation icon appears on top of everything else. Add something like this to the CSS for the translation icon:
z-index: 1000;

**Comment by berthelemy** [comment] 2022-06-07 13:16
@jgramp Sorry for the delayed reply.

I've checked the source HTML and the icon isn't there at all. It's appearing on activities in Section 0 (ie. not inside a tile), but not on any activity that is inside a tile.

The only way to see them is to put the course into edit mode, but I don't want translators to be able to edit the course.

Even then, the translation icon doesn't always appear on the topic titles (see screenshot):

![image](https://user-images.githubusercontent.com/2512079/172389338-4ffb2c95-d32d-45ce-8a33-9f6a9495e4ba.png)

I think this issue is linked to, or even duplicated by #114

**Comment by andrewhancox** [comment] 2022-06-17 09:14
Definitely a duplicate of 114

**Closed by andrewhancox** 2022-06-17 09:14 UTC
