### ISSUE TITLE
Warnings when upgrading to latest version

### ISSUE THREAD

**Issue by rjnl** [andrewhancox/moodle-filter_translations#84] opened 2022-05-03 04:06 UTC
We get these warnings when upgrading to version 2022042700 from 2022022321 on Moodle 3.11.x

Coding problem: $PAGE->context was not set. You may have forgotten to call require_login() or $PAGE->set_context(). The page may not display correctly as a result
line 503 of \lib\pagelib.php: call to debugging()
line 830 of \lib\pagelib.php: call to moodle_page->magic_get_context()
line 195 of \filter\translations\filter.php: call to moodle_page->__get()
line 155 of \filter\translations\lib.php: call to filter_translations::checkinlinestranslation()
line 1064 of \lib\setup.php: call to filter_translations_after_config()
line 33 of \config.php: call to require_once()
line 88 of \admin\index.php: call to require()
Capability "filter/translations:editsitedefaulttranslations" was not found! This has to be fixed in code.
line 453 of \lib\accesslib.php: call to debugging()
line 195 of \filter\translations\filter.php: call to has_capability()
line 155 of \filter\translations\lib.php: call to filter_translations::checkinlinestranslation()
line 1064 of \lib\setup.php: call to filter_translations_after_config()
line 33 of \config.php: call to require_once()
line 88 of \admin\index.php: call to require()

**Comment by andrewhancox** [comment] 2022-05-03 12:17
I was unable to reproduce the issue but have pushed a fix that should fix this. Can you test and confirm?

**Comment by rjnl** [comment] 2022-05-04 08:42
I'm able to reproduce this after purging the cache.

This page context warning disappears after commenting out  filter_translations_after_config() since a call to filter_translations::checkinlinestranslation() is where this warning is generated. After the page has loaded successfully this warning is not generated even after adding back the filter_translations_after_config() function.
But if you purge the Moodle cache the warning is back.

**Comment by andrewhancox** [comment] 2022-05-05 13:41
Fixed

**Closed by andrewhancox** 2022-05-05 13:41 UTC
