### ISSUE TITLE
Categories and some courses not filtered for content translations

### ISSUE THREAD

**Issue by berthelemy** [andrewhancox/moodle-filter_translations#116] opened 2022-06-08 09:19 UTC
## Settings

- Google translate API working
- Filter set to Content and Headings
- Theme pack: Moove
- Course format: Tiles

## Scenario

1. Switch to a language other than the default
2. Turn on inline translation
3. Go to a course category with descriptive text
4. Go to a course

## Expected behaviour

1. The course category and its description should be translated to the target language, and have a translate button next to each component
2. The course content should be translated to the target language, and have a translate button next to each component

## Actual behaviour

- No course category pages are being translated or have translate buttons (see screenshot 1)
- Some courses are being translated, others not. They all use the same course format (see screenshots 2 & 3)

## Screenshot 1: Category page

![image](https://user-images.githubusercontent.com/2512079/172580084-bb110dd7-66ce-4a82-b9de-1f459b06b175.png)

## Screenshot 2: Translated course 

(Except for the elements where there is the known conflict with Tiles See: #114 )

![image](https://user-images.githubusercontent.com/2512079/172580561-27a2a0a9-5f30-48bb-b09f-96b8bc30802e.png)
 
## Screenshot 3: Non-translated course

Same course format, same category

![image](https://user-images.githubusercontent.com/2512079/172580797-3e0e04ce-bea8-4cfe-befe-7ffaebe7999a.png)

**Comment by andrewhancox** [comment] 2022-06-17 09:07
There was a serious bug in the caching that is now fixed - my suspicion is this was the root cause here.

**Closed** 2022-07-14 12:10 UTC
